### ISSUE TITLE
babel-runtime dep

### ISSUE THREAD

**Issue by nicknikolov** [novemberborn/identifierfy#35]
Hey dude,

just wanted to double check something with you. I found your module inside my dep tree and you have the `babel-runtime` dep in your package-json but I don't actually see you use it in the source? Is it needed? Or maybe it could be moved to depDepenedencies? It's a rather large dep in size so I was wondering if we can somehow prune it.

Thanks!

**Comment by novemberborn** [comment]
This is a pretty old package so it's probably there to support a Babel transform.

Happy to take a PR which gets rid of Babel and targets Node.js 6 and above.

**Comment by novemberborn** [comment]
Thanks to @goto-bus-stop for opening https://github.com/novemberborn/identifierfy/pull/36.

This has landed and `v2.0.0` is now available.
